// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAol2MmQz8ER_mEzIvm_PwCTvhHm3jcLgc',
    appId: '1:263813394615:web:c8558e2912ba8ef9881d32',
    messagingSenderId: '263813394615',
    projectId: 'social-media-app-98a02',
    authDomain: 'social-media-app-98a02.firebaseapp.com',
    storageBucket: 'social-media-app-98a02.firebasestorage.app',
    measurementId: 'G-RFN0VRX50N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQBal-AlK4_pZVVbUjq9VuCZV7wQuvH50',
    appId: '1:263813394615:android:0df76eb3ff4221c3881d32',
    messagingSenderId: '263813394615',
    projectId: 'social-media-app-98a02',
    storageBucket: 'social-media-app-98a02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeVbnTr1MOYJnoF8LLnygkL4MlruD3Thk',
    appId: '1:263813394615:ios:d2165b874ac3ca80881d32',
    messagingSenderId: '263813394615',
    projectId: 'social-media-app-98a02',
    storageBucket: 'social-media-app-98a02.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaAppUsingFirebase',
  );
}
